apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: registry,ocp4.example.com:8443/redhattraining/hello-world-nginx:latest
    ports:
    - containerPort: 80
